def addData(game):
    game.addTile( IndoorTile, 'Bathroom', DOOR, BLOCKED, BLOCKED, BLOCKED, NO_MESSAGE )
    game.addTile( IndoorTile, 'Kitchen', DOOR, DOOR, BLOCKED, DOOR, '+1 health if end move here' )
    game.addTile( IndoorTile, 'Storage', DOOR, BLOCKED, BLOCKED, BLOCKED, 'may search for an item here' )
    game.addTile( IndoorTile, 'Evil Temple', BLOCKED, DOOR, BLOCKED, DOOR, 'can search for the totem here')
    game.addTile( IndoorTile, 'Family Room', DOOR, DOOR, BLOCKED, DOOR, NO_MESSAGE )
    game.addTile( IndoorTile, 'Dining Room', DOOR, DOOR, DOOR, DOOR, NO_MESSAGE )
    game.addTile( IndoorTile, 'Bedroom', DOOR, BLOCKED, BLOCKED, DOOR, NO_MESSAGE )
    game.addTile( IndoorTile, 'Foyer', DOOR, BLOCKED, BLOCKED, BLOCKED, NO_MESSAGE )
    #outdoors
    game.addTile( OutdoorTile, 'Garden', HEDGE, OPEN, OPEN, OPEN, '+1 Health of end turn here' )
    game.addTile( OutdoorTile, 'Sitting Area', HEDGE, OPEN, OPEN, OPEN, NO_MESSAGE )
    game.addTile( OutdoorTile, 'Yard01', HEDGE, OPEN, OPEN, OPEN, NO_MESSAGE )
    game.addTile( OutdoorTile, 'Graveyard', HEDGE, OPEN, OPEN, HEDGE, 'Can bury the totem here' )
    game.addTile( OutdoorTile, 'Garage', HEDGE, HEDGE, OPEN, OPEN, NO_MESSAGE )
    game.addTile( OutdoorTile, 'Patio', DOOR, OPEN, OPEN, HEDGE, NO_MESSAGE )
    game.addTile( OutdoorTile, 'Yard02', HEDGE, OPEN, OPEN, OPEN, NO_MESSAGE )
    game.addTile( OutdoorTile, 'Yard03', HEDGE, OPEN, OPEN, OPEN, NO_MESSAGE )
    
    game.setStartTile( 'Foyer' )
    game.setTileAside( 'Patio' )
    
    game.addItem( 'Oil' , None, "not sure", 1)
    game.addItem( 'Gasoline', None, "not sure", 1)
    game.addItem( 'Board with Nails', 2, "not sure", -1)
    game.addItem( 'Machette', 3, "not sure", -1)
    game.addItem( 'Grisly Femur', 2, "not sure", -1)
    game.addItem( 'Golf Club', 2, "not sure", -1)
    game.addItem( 'Chainsaw', 2, "not sure", -1)
    game.addItem( 'Can of Soda', None, "not sure", 1)
    game.addItem( 'Candle', None, "not sure", 1)
    
    game.addActionCard(game.allItems['Oil'], ( 'You try hard not to wet yourself', 0 ), 'item', 6)
    game.addActionCard(game.allItems['Gasoline'], 4, ( 'You sense your impending doom',  -1 ), 'item')
    game.addActionCard(game.allItems['Board with Nails'], 'item', 4, ( 'Something icky in your mouth', -1 ))
    game.addActionCard(game.allItems['Machette'], 4, ( 'A bat poops in your eye', -1 ), 6)
    game.addActionCard(game.allItems['Grisly Femur'], 'item', 5, ( 'Your sould is not wanted here', -1 ))
    game.addActionCard(game.allItems['Golf Club'], ( 'Slip on nasty goo', -1 ), 4, ( 'The smell of blood is in the air', 0 ))  
    game.addActionCard(game.allItems['Chainsaw'], 3, ( 'you hear terrible screams', 0 ), 5)
    game.addActionCard(game.allItems['Can of Soda'], ( 'Candy bar in your pocket', +1 ), 'item', 4)
    game.addActionCard(game.allItems['Candle'], ( 'Your body shivers involuntarily', 0 ), ( 'You feel a spark of hope', +1 ), 4)